.tag-container:
  tags:
    - kubernetes
  stage: tag
  variables:
    SOURCE_TAG: v$CI_COMMIT_REF_SLUG
    DEST_TAG: $CI_COMMIT_SHORT_SHA
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: ['']
  script:
    - crane cp $IMAGE_NAME:$SOURCE_TAG $IMAGE_NAME:$DEST_TAG

.build-container:
  tags:
    - kubernetes
  stage: build-containers
  image:
    name: img.conny.dev/oss/kaniko/executor:debug
    # name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    TAG: v$CI_COMMIT_REF_SLUG
    PROJECT_DIR: $CI_PROJECT_DIR
    DOCKERFILE: Dockerfile.p
  script:
    - echo $DOCKERFILE
    - /kaniko/executor --cache=true
                       --context $PROJECT_DIR
                       --dockerfile $PROJECT_DIR/$DOCKERFILE
                       --label 'git-branch'=$CI_COMMIT_REF_SLUG
                       --label 'git-tag=$CI_COMMIT_TAG'
                       --destination $IMAGE_NAME:$TAG
